// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetBookName(translation: string, bookNumber: number): $CancellablePromise<string> {
    return $Call.ByID(3943492079, translation, bookNumber);
}

export function GetBooks(translation: string): $CancellablePromise<$models.Book[]> {
    return $Call.ByID(3787447781, translation).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetChapters(translation: string, bookNumber: number): $CancellablePromise<number[]> {
    return $Call.ByID(497574175, translation, bookNumber).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetInfo(translation: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1822448697, translation).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetTranslations(): $CancellablePromise<$models.TranslationInfo[]> {
    return $Call.ByID(1383695849).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetVerse(translation: string, bookNumber: number, chapter: number, verse: number): $CancellablePromise<$models.Verse | null> {
    return $Call.ByID(2764956254, translation, bookNumber, chapter, verse).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetVerses(translation: string, bookNumber: number, chapter: number): $CancellablePromise<$models.Verse[]> {
    return $Call.ByID(2635795671, translation, bookNumber, chapter).then(($result: any) => {
        return $$createType8($result);
    });
}

export function Search(translation: string, query: string): $CancellablePromise<$models.SearchResult[]> {
    return $Call.ByID(2094383895, translation, query).then(($result: any) => {
        return $$createType10($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Book.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $models.TranslationInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.Verse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType6);
const $$createType9 = $models.SearchResult.createFrom;
const $$createType10 = $Create.Array($$createType9);
