// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddBookmark(bookmark: $models.Bookmark): $CancellablePromise<$models.Bookmark> {
    return $Call.ByID(3178229703, bookmark).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AddHighlight(highlight: $models.Highlight): $CancellablePromise<$models.Highlight> {
    return $Call.ByID(3086098241, highlight).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetBookmarks(): $CancellablePromise<$models.Bookmark[]> {
    return $Call.ByID(2686501757).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetHighlights(): $CancellablePromise<$models.Highlight[]> {
    return $Call.ByID(1335209533).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RemoveBookmark(id: number): $CancellablePromise<void> {
    return $Call.ByID(4151116544, id);
}

export function RemoveHighlight(id: number): $CancellablePromise<void> {
    return $Call.ByID(4174628624, id);
}

export function UpdateBookmarkNote(id: number, note: string): $CancellablePromise<void> {
    return $Call.ByID(1148137485, id, note);
}

// Private type creation functions
const $$createType0 = $models.Bookmark.createFrom;
const $$createType1 = $models.Highlight.createFrom;
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $Create.Array($$createType1);
