// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddBookmark(bookmark: $models.Bookmark): $CancellablePromise<$models.Bookmark> {
    return $Call.ByID(3178229703, bookmark).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AddHighlight(highlight: $models.Highlight): $CancellablePromise<$models.Highlight> {
    return $Call.ByID(3086098241, highlight).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AddNote(note: $models.Note): $CancellablePromise<$models.Note> {
    return $Call.ByID(813953515, note).then(($result: any) => {
        return $$createType2($result);
    });
}

export function AddToVerseList(listID: number, bookNumber: number, chapter: number, verse: number): $CancellablePromise<$models.VerseListItem> {
    return $Call.ByID(2822770851, listID, bookNumber, chapter, verse).then(($result: any) => {
        return $$createType3($result);
    });
}

export function CreateVerseList(translation: string, name: string): $CancellablePromise<$models.VerseList> {
    return $Call.ByID(713341981, translation, name).then(($result: any) => {
        return $$createType4($result);
    });
}

export function DeleteVerseList(id: number): $CancellablePromise<void> {
    return $Call.ByID(1452748728, id);
}

export function GetBookmarks(): $CancellablePromise<$models.Bookmark[]> {
    return $Call.ByID(2686501757).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetHighlights(): $CancellablePromise<$models.Highlight[]> {
    return $Call.ByID(1335209533).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetNoteForVerse(bookNumber: number, chapter: number, verse: number): $CancellablePromise<$models.Note | null> {
    return $Call.ByID(867322092, bookNumber, chapter, verse).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetNotes(): $CancellablePromise<$models.Note[]> {
    return $Call.ByID(2679791129).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetVerseListItems(translation: string, listID: number): $CancellablePromise<$models.VerseListItem[]> {
    return $Call.ByID(4180415, translation, listID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetVerseLists(translation: string): $CancellablePromise<$models.VerseList[]> {
    return $Call.ByID(3954414706, translation).then(($result: any) => {
        return $$createType10($result);
    });
}

export function RemoveBookmark(id: number): $CancellablePromise<void> {
    return $Call.ByID(4151116544, id);
}

export function RemoveFromVerseList(listID: number, itemID: number): $CancellablePromise<void> {
    return $Call.ByID(1502639649, listID, itemID);
}

export function RemoveHighlight(id: number): $CancellablePromise<void> {
    return $Call.ByID(4174628624, id);
}

export function RemoveNote(id: number): $CancellablePromise<void> {
    return $Call.ByID(2084160924, id);
}

export function UpdateBookmarkNote(id: number, note: string): $CancellablePromise<void> {
    return $Call.ByID(1148137485, id, note);
}

export function UpdateNoteContent(id: number, content: string): $CancellablePromise<void> {
    return $Call.ByID(1480348438, id, content);
}

// Private type creation functions
const $$createType0 = $models.Bookmark.createFrom;
const $$createType1 = $models.Highlight.createFrom;
const $$createType2 = $models.Note.createFrom;
const $$createType3 = $models.VerseListItem.createFrom;
const $$createType4 = $models.VerseList.createFrom;
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = $Create.Array($$createType1);
const $$createType7 = $Create.Nullable($$createType2);
const $$createType8 = $Create.Array($$createType2);
const $$createType9 = $Create.Array($$createType3);
const $$createType10 = $Create.Array($$createType4);
