// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAvailableCommentaries(translation: string): $CancellablePromise<$models.CommentaryInfo[]> {
    return $Call.ByID(1077164678, translation).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetCommentaryForChapter(translation: string, bookNumber: number, chapter: number): $CancellablePromise<$models.CommentaryEntry[]> {
    return $Call.ByID(2095645197, translation, bookNumber, chapter).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetCommentaryForVerse(translation: string, bookNumber: number, chapter: number, verse: number): $CancellablePromise<$models.CommentaryEntry[]> {
    return $Call.ByID(2439228285, translation, bookNumber, chapter, verse).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Preload(): $CancellablePromise<void> {
    return $Call.ByID(4245136285);
}

// Private type creation functions
const $$createType0 = $models.CommentaryInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.CommentaryEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
