// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function EntryCount(): $CancellablePromise<number> {
    return $Call.ByID(1452611678);
}

export function GetCurrentDictionary(): $CancellablePromise<string> {
    return $Call.ByID(1501456120);
}

export function GetDefinition(topic: string): $CancellablePromise<string> {
    return $Call.ByID(662928678, topic);
}

export function GetDictionaries(): $CancellablePromise<string[]> {
    return $Call.ByID(3818162531).then(($result: any) => {
        return $$createType0($result);
    });
}

export function LookupCognates(topic: string): $CancellablePromise<$models.DictionaryEntry[]> {
    return $Call.ByID(3503495229, topic).then(($result: any) => {
        return $$createType2($result);
    });
}

export function LookupTopic(topic: string): $CancellablePromise<$models.DictionaryEntry[]> {
    return $Call.ByID(550198546, topic).then(($result: any) => {
        return $$createType2($result);
    });
}

export function LookupTopicPrefix(prefix: string): $CancellablePromise<$models.DictionaryEntry[]> {
    return $Call.ByID(2096594838, prefix).then(($result: any) => {
        return $$createType2($result);
    });
}

export function LookupWord(word: string): $CancellablePromise<$models.DictionaryEntry[]> {
    return $Call.ByID(3008063939, word).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Preload(): $CancellablePromise<void> {
    return $Call.ByID(1719168770);
}

export function SearchPhrase(phrase: string): $CancellablePromise<$models.DictionaryEntry[]> {
    return $Call.ByID(1726594328, phrase).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetDictionary(name: string): $CancellablePromise<boolean> {
    return $Call.ByID(357915303, name);
}

export function WordCount(): $CancellablePromise<number> {
    return $Call.ByID(3460487904);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.DictionaryEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
