// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function EntryCount(): $CancellablePromise<number> {
    return $Call.ByID(1452611678);
}

export function GetDefinition(topic: string): $CancellablePromise<string> {
    return $Call.ByID(662928678, topic);
}

export function LookupTopic(topic: string): $CancellablePromise<$models.DictionaryEntry[]> {
    return $Call.ByID(550198546, topic).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LookupWord(word: string): $CancellablePromise<$models.DictionaryEntry[]> {
    return $Call.ByID(3008063939, word).then(($result: any) => {
        return $$createType1($result);
    });
}

export function WordCount(): $CancellablePromise<number> {
    return $Call.ByID(3460487904);
}

// Private type creation functions
const $$createType0 = $models.DictionaryEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
