// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as BibleService from "./bibleservice.js";
import * as BookmarksService from "./bookmarksservice.js";
import * as DictionaryService from "./dictionaryservice.js";
export {
    BibleService,
    BookmarksService,
    DictionaryService
};

export {
    Book,
    Bookmark,
    DictionaryEntry,
    Highlight,
    SearchResult,
    TranslationInfo,
    Verse
} from "./models.js";
