// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function EntryCount(): $CancellablePromise<number> {
    return $Call.ByID(3397995981);
}

export function GetAllMaps(): $CancellablePromise<$models.MapEntry[]> {
    return $Call.ByID(1568147458).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetLocationEntries(): $CancellablePromise<$models.MapEntry[]> {
    return $Call.ByID(2895696695).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetMapEntry(topic: string): $CancellablePromise<$models.MapEntry> {
    return $Call.ByID(1290894896, topic).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetMapImage(id: string): $CancellablePromise<string> {
    return $Call.ByID(154003929, id);
}

export function Preload(): $CancellablePromise<void> {
    return $Call.ByID(3124348503);
}

export function SearchLocations(query: string): $CancellablePromise<$models.MapEntry[]> {
    return $Call.ByID(2379894058, query).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SearchMaps(query: string): $CancellablePromise<$models.MapEntry[]> {
    return $Call.ByID(917145465, query).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.MapEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
