// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Book {
    "bookNumber": number;
    "shortName": string;
    "longName": string;
    "color": string;
    "chapterCount": number;

    /** Creates a new Book instance. */
    constructor($$source: Partial<Book> = {}) {
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("shortName" in $$source)) {
            this["shortName"] = "";
        }
        if (!("longName" in $$source)) {
            this["longName"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("chapterCount" in $$source)) {
            this["chapterCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Book instance from a string or object.
     */
    static createFrom($$source: any = {}): Book {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Book($$parsedSource as Partial<Book>);
    }
}

export class Bookmark {
    "id": number;
    "bookNumber": number;
    "chapter": number;
    "verse": number;
    "translation": string;
    "note": string;
    "createdAt": string;

    /** Creates a new Bookmark instance. */
    constructor($$source: Partial<Bookmark> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            this["verse"] = 0;
        }
        if (!("translation" in $$source)) {
            this["translation"] = "";
        }
        if (!("note" in $$source)) {
            this["note"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bookmark instance from a string or object.
     */
    static createFrom($$source: any = {}): Bookmark {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Bookmark($$parsedSource as Partial<Bookmark>);
    }
}

export class CommentaryEntry {
    "bookNumber": number;
    "chapterFrom": number;
    "verseFrom": number;
    "chapterTo": number;
    "verseTo": number;
    "marker": string;
    "text": string;
    "source": string;

    /** Creates a new CommentaryEntry instance. */
    constructor($$source: Partial<CommentaryEntry> = {}) {
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapterFrom" in $$source)) {
            this["chapterFrom"] = 0;
        }
        if (!("verseFrom" in $$source)) {
            this["verseFrom"] = 0;
        }
        if (!("chapterTo" in $$source)) {
            this["chapterTo"] = 0;
        }
        if (!("verseTo" in $$source)) {
            this["verseTo"] = 0;
        }
        if (!("marker" in $$source)) {
            this["marker"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommentaryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): CommentaryEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommentaryEntry($$parsedSource as Partial<CommentaryEntry>);
    }
}

export class CommentaryInfo {
    "name": string;
    "displayName": string;
    "fileName": string;

    /** Creates a new CommentaryInfo instance. */
    constructor($$source: Partial<CommentaryInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommentaryInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CommentaryInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommentaryInfo($$parsedSource as Partial<CommentaryInfo>);
    }
}

export class DictionaryEntry {
    "topic": string;
    "shortDef": string;
    "lexeme": string;
    "transliteration": string;
    "pronunciation": string;
    "definition": string;
    "cognates": DictionaryEntry[];

    /** Creates a new DictionaryEntry instance. */
    constructor($$source: Partial<DictionaryEntry> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("shortDef" in $$source)) {
            this["shortDef"] = "";
        }
        if (!("lexeme" in $$source)) {
            this["lexeme"] = "";
        }
        if (!("transliteration" in $$source)) {
            this["transliteration"] = "";
        }
        if (!("pronunciation" in $$source)) {
            this["pronunciation"] = "";
        }
        if (!("definition" in $$source)) {
            this["definition"] = "";
        }
        if (!("cognates" in $$source)) {
            this["cognates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DictionaryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DictionaryEntry {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cognates" in $$parsedSource) {
            $$parsedSource["cognates"] = $$createField6_0($$parsedSource["cognates"]);
        }
        return new DictionaryEntry($$parsedSource as Partial<DictionaryEntry>);
    }
}

export class Highlight {
    "id": number;
    "bookNumber": number;
    "chapter": number;
    "verse": number;
    "color": string;
    "translation": string;
    "createdAt": string;

    /** Creates a new Highlight instance. */
    constructor($$source: Partial<Highlight> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            this["verse"] = 0;
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("translation" in $$source)) {
            this["translation"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Highlight instance from a string or object.
     */
    static createFrom($$source: any = {}): Highlight {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Highlight($$parsedSource as Partial<Highlight>);
    }
}

export class MapEntry {
    "topic": string;
    "definition": string;

    /** Creates a new MapEntry instance. */
    constructor($$source: Partial<MapEntry> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("definition" in $$source)) {
            this["definition"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MapEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): MapEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MapEntry($$parsedSource as Partial<MapEntry>);
    }
}

export class Note {
    "id": number;
    "bookNumber": number;
    "chapter": number;
    "verse": number;
    "content": string;
    "translation": string;
    "createdAt": string;

    /** Creates a new Note instance. */
    constructor($$source: Partial<Note> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            this["verse"] = 0;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("translation" in $$source)) {
            this["translation"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     */
    static createFrom($$source: any = {}): Note {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Note($$parsedSource as Partial<Note>);
    }
}

export class PlanDayJSON {
    "day": number;
    "readings": ReadingJSON[];

    /** Creates a new PlanDayJSON instance. */
    constructor($$source: Partial<PlanDayJSON> = {}) {
        if (!("day" in $$source)) {
            this["day"] = 0;
        }
        if (!("readings" in $$source)) {
            this["readings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanDayJSON instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanDayJSON {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("readings" in $$parsedSource) {
            $$parsedSource["readings"] = $$createField1_0($$parsedSource["readings"]);
        }
        return new PlanDayJSON($$parsedSource as Partial<PlanDayJSON>);
    }
}

export class PlanProgress {
    "id": number;
    "planId": string;
    "bookNumber": number;
    "chapter": number;
    "completedAt": string;

    /** Creates a new PlanProgress instance. */
    constructor($$source: Partial<PlanProgress> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("planId" in $$source)) {
            this["planId"] = "";
        }
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlanProgress($$parsedSource as Partial<PlanProgress>);
    }
}

export class ReadingJSON {
    "bookNumber": number;
    "chapter": number;

    /** Creates a new ReadingJSON instance. */
    constructor($$source: Partial<ReadingJSON> = {}) {
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadingJSON instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadingJSON {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadingJSON($$parsedSource as Partial<ReadingJSON>);
    }
}

export class ReadingPlanJSON {
    "id": string;
    "name": string;
    "days": PlanDayJSON[];

    /** Creates a new ReadingPlanJSON instance. */
    constructor($$source: Partial<ReadingPlanJSON> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("days" in $$source)) {
            this["days"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadingPlanJSON instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadingPlanJSON {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("days" in $$parsedSource) {
            $$parsedSource["days"] = $$createField2_0($$parsedSource["days"]);
        }
        return new ReadingPlanJSON($$parsedSource as Partial<ReadingPlanJSON>);
    }
}

export class SearchResult {
    "bookNumber": number;
    "chapter": number;
    "verse": number;
    "text": string;
    "bookName": string;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            this["verse"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("bookName" in $$source)) {
            this["bookName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

export class TopicListItem {
    "topic": string;

    /** Creates a new TopicListItem instance. */
    constructor($$source: Partial<TopicListItem> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicListItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicListItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopicListItem($$parsedSource as Partial<TopicListItem>);
    }
}

export class TopicalEntry {
    "topic": string;
    "definition": string;

    /** Creates a new TopicalEntry instance. */
    constructor($$source: Partial<TopicalEntry> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("definition" in $$source)) {
            this["definition"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicalEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicalEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopicalEntry($$parsedSource as Partial<TopicalEntry>);
    }
}

export class TopicalVerseRef {
    "bookNumber": number;
    "chapter": number;
    "verse": number;
    "reference": string;

    /** Creates a new TopicalVerseRef instance. */
    constructor($$source: Partial<TopicalVerseRef> = {}) {
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            this["verse"] = 0;
        }
        if (!("reference" in $$source)) {
            this["reference"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicalVerseRef instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicalVerseRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopicalVerseRef($$parsedSource as Partial<TopicalVerseRef>);
    }
}

export class TranslationInfo {
    "name": string;
    "displayName": string;
    "fileName": string;

    /** Creates a new TranslationInfo instance. */
    constructor($$source: Partial<TranslationInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslationInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslationInfo($$parsedSource as Partial<TranslationInfo>);
    }
}

export class Verse {
    "bookNumber": number;
    "chapter": number;
    "verse": number;
    "text": string;

    /** Creates a new Verse instance. */
    constructor($$source: Partial<Verse> = {}) {
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            this["verse"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Verse instance from a string or object.
     */
    static createFrom($$source: any = {}): Verse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Verse($$parsedSource as Partial<Verse>);
    }
}

export class VerseList {
    "id": number;
    "name": string;
    "translation": string;
    "createdAt": string;

    /** Creates a new VerseList instance. */
    constructor($$source: Partial<VerseList> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("translation" in $$source)) {
            this["translation"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VerseList instance from a string or object.
     */
    static createFrom($$source: any = {}): VerseList {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VerseList($$parsedSource as Partial<VerseList>);
    }
}

export class VerseListItem {
    "id": number;
    "listId": number;
    "bookNumber": number;
    "chapter": number;
    "verse": number;
    "sortOrder": number;
    "createdAt": string;

    /** Creates a new VerseListItem instance. */
    constructor($$source: Partial<VerseListItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("listId" in $$source)) {
            this["listId"] = 0;
        }
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            this["verse"] = 0;
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VerseListItem instance from a string or object.
     */
    static createFrom($$source: any = {}): VerseListItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VerseListItem($$parsedSource as Partial<VerseListItem>);
    }
}

// Private type creation functions
const $$createType0 = DictionaryEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ReadingJSON.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = PlanDayJSON.createFrom;
const $$createType5 = $Create.Array($$createType4);
