// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Book {
    "bookNumber": number;
    "shortName": string;
    "longName": string;
    "color": string;
    "chapterCount": number;

    /** Creates a new Book instance. */
    constructor($$source: Partial<Book> = {}) {
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("shortName" in $$source)) {
            this["shortName"] = "";
        }
        if (!("longName" in $$source)) {
            this["longName"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("chapterCount" in $$source)) {
            this["chapterCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Book instance from a string or object.
     */
    static createFrom($$source: any = {}): Book {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Book($$parsedSource as Partial<Book>);
    }
}

export class Bookmark {
    "id": number;
    "bookNumber": number;
    "chapter": number;
    "verse": number;
    "translation": string;
    "note": string;
    "createdAt": string;

    /** Creates a new Bookmark instance. */
    constructor($$source: Partial<Bookmark> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            this["verse"] = 0;
        }
        if (!("translation" in $$source)) {
            this["translation"] = "";
        }
        if (!("note" in $$source)) {
            this["note"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bookmark instance from a string or object.
     */
    static createFrom($$source: any = {}): Bookmark {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Bookmark($$parsedSource as Partial<Bookmark>);
    }
}

export class DictionaryEntry {
    "topic": string;
    "shortDef": string;
    "lexeme": string;
    "transliteration": string;
    "pronunciation": string;
    "definition": string;

    /** Creates a new DictionaryEntry instance. */
    constructor($$source: Partial<DictionaryEntry> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("shortDef" in $$source)) {
            this["shortDef"] = "";
        }
        if (!("lexeme" in $$source)) {
            this["lexeme"] = "";
        }
        if (!("transliteration" in $$source)) {
            this["transliteration"] = "";
        }
        if (!("pronunciation" in $$source)) {
            this["pronunciation"] = "";
        }
        if (!("definition" in $$source)) {
            this["definition"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DictionaryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DictionaryEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DictionaryEntry($$parsedSource as Partial<DictionaryEntry>);
    }
}

export class Highlight {
    "id": number;
    "bookNumber": number;
    "chapter": number;
    "verse": number;
    "color": string;
    "translation": string;
    "createdAt": string;

    /** Creates a new Highlight instance. */
    constructor($$source: Partial<Highlight> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            this["verse"] = 0;
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("translation" in $$source)) {
            this["translation"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Highlight instance from a string or object.
     */
    static createFrom($$source: any = {}): Highlight {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Highlight($$parsedSource as Partial<Highlight>);
    }
}

export class SearchResult {
    "bookNumber": number;
    "chapter": number;
    "verse": number;
    "text": string;
    "bookName": string;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            this["verse"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("bookName" in $$source)) {
            this["bookName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

export class TranslationInfo {
    "name": string;
    "displayName": string;
    "fileName": string;

    /** Creates a new TranslationInfo instance. */
    constructor($$source: Partial<TranslationInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslationInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslationInfo($$parsedSource as Partial<TranslationInfo>);
    }
}

export class Verse {
    "bookNumber": number;
    "chapter": number;
    "verse": number;
    "text": string;

    /** Creates a new Verse instance. */
    constructor($$source: Partial<Verse> = {}) {
        if (!("bookNumber" in $$source)) {
            this["bookNumber"] = 0;
        }
        if (!("chapter" in $$source)) {
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            this["verse"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Verse instance from a string or object.
     */
    static createFrom($$source: any = {}): Verse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Verse($$parsedSource as Partial<Verse>);
    }
}
