// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAllPlans(): $CancellablePromise<$models.ReadingPlanJSON[]> {
    return $Call.ByID(3421963119).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetPlan(planID: string): $CancellablePromise<$models.ReadingPlanJSON | null> {
    return $Call.ByID(3812181449, planID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetProgress(planID: string): $CancellablePromise<$models.PlanProgress[]> {
    return $Call.ByID(2703516701, planID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function IsChapterDone(planID: string, bookNumber: number, chapter: number): $CancellablePromise<boolean> {
    return $Call.ByID(3558155055, planID, bookNumber, chapter);
}

export function MarkChapter(planID: string, bookNumber: number, chapter: number): $CancellablePromise<void> {
    return $Call.ByID(3354322224, planID, bookNumber, chapter);
}

export function SavePlan(plan: $models.ReadingPlanJSON): $CancellablePromise<void> {
    return $Call.ByID(301864668, plan);
}

export function UnmarkChapter(planID: string, bookNumber: number, chapter: number): $CancellablePromise<void> {
    return $Call.ByID(2992578613, planID, bookNumber, chapter);
}

// Private type creation functions
const $$createType0 = $models.ReadingPlanJSON.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType0);
const $$createType3 = $models.PlanProgress.createFrom;
const $$createType4 = $Create.Array($$createType3);
