// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CleanDefinition strips HTML tags but preserves verse reference text
 */
export function CleanDefinition(definition: string): $CancellablePromise<string> {
    return $Call.ByID(1855261653, definition);
}

export function EntryCount(): $CancellablePromise<number> {
    return $Call.ByID(621841384);
}

export function GetAlphabetIndex(): $CancellablePromise<{ [_ in string]?: number }> {
    return $Call.ByID(1975536082).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetTopicDefinition(topic: string): $CancellablePromise<string> {
    return $Call.ByID(812193737, topic);
}

export function GetTopicsByLetter(letter: string): $CancellablePromise<$models.TopicListItem[]> {
    return $Call.ByID(3884952640, letter).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ParseVerseRefs extracts Bible verse references from Nave's HTML definition
 * Format: <a href='B:NNN CH:V'>Reference Text</a>
 */
export function ParseVerseRefs(definition: string): $CancellablePromise<$models.TopicalVerseRef[]> {
    return $Call.ByID(2429381033, definition).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Preload(): $CancellablePromise<void> {
    return $Call.ByID(464958220);
}

export function SearchTopics(query: string): $CancellablePromise<$models.TopicalEntry[]> {
    return $Call.ByID(11740123, query).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.TopicListItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.TopicalVerseRef.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.TopicalEntry.createFrom;
const $$createType6 = $Create.Array($$createType5);
